### ISSUE TITLE
(Question) Is a new release going to be added to download?

### ISSUE THREAD

**Issue by MaximusXgamer** [Kirby144p/ModpackDownloader#1]
I am looking for the jar file that I have to download, but I cannot see any releases which can be used. Could you upload a release to use?

**Comment by Kirby144p** [comment]
Thank You for Your comment!
I've uploaded a release of ModpackDownloader.
Please note that Java 17 or higher is required to execute the jar-file.
If You have any issues, feel free to open another issue here on GitHub.
